#!/bin/sh
#Vaihdetaan tietokoneen oma näyttö päänäytöksi, koska muuten tulee ongelmia
eDP=`xrandr |grep -o '.* connected' |grep -o '^e\S*'`
[ ${eDP} ] && xrandr --output ${eDP} --auto --primary
[ $TAUSTA ] || TAUSTA='-solid #000000'
hsetroot $TAUSTA

echo deep |sudo tee /sys/power/mem_sleep
slock echo mem |sudo tee /sys/power/state
